### PR TITLE
fix #37: better upload error handling

### LINKED ISSUE #37: properly handle error when max upload size exceeded
(currently shows wrong message)

### PR DESCRIPTION
**Pull request by kirlen**
- update to latest bee-js
 - handle 413 error explicitly
 - tweak styling

### CODE REVIEW

File: client/src/components/archive-save/archive-save.tsx [hunk 1]
```diff
@@ -32,6 +32,18 @@ export default function ArchiveSave() {
   };
   const copy = hash && hash.length > 0 ? "Backed up to Swarm" : "Not yet backed up to Swarm.";
   const socialArchiveUrl = (url || '').replace('https://gateway.ethswarm.org/access/', '/archive/');
```
Comment (ameer-clara) [inline client/src/components/archive-save/archive-save.tsx:34]: @codiak - Instead of using url and hardcoding replacing gateway host, advise to use window.location.origin + '/archive/' + hash instead.

File: client/package.json [hunk 2]
```diff
@@ -3,7 +3,7 @@
   "version": "0.1.0",
   "private": true,
   "dependencies": {
-    "@ethersphere/bee-js": "^3.1.0",
+    "@ethersphere/bee-js": "^3.2.0",
```
Comment (codiak) [inline client/package.json:6]: Nice 🏆

File: client/src/components/archive-save/archive-save.tsx (hunk 1 above)
Comment (codiak) [reply client/src/components/archive-save/archive-save.tsx:34]: Yeah this is a little hacky, really we should just pass the hash through and build the URLs in the display component. Although socialArchiveUrl in particular should be relative.

**Review by codiak — APPROVED** [review]
